version: '3.7'
services:
  node:
    restart: always
    build: .
    environment:
        - SERVER_PORT=3000
        - MONGO_URL=mongodb://mongo:27017/node
    ports:
      - 3000:3000
    volumes:
      - ./:/code
  mongo:
    image: mongo:latest
    environment:
        - MONGO_INITDB_DATABASE=node
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:


